# Generated by Django 5.0.6 on 2024-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_data',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=100)),
                ('admin_password', models.CharField(max_length=20)),
                ('admin_gender', models.CharField(max_length=10)),
                ('admin_role', models.CharField(max_length=20)),
                ('admin_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_data',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_category', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='productimage/')),
            ],
        ),
    ]
