# Generated by Django 5.0.6 on 2024-07-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='customer_address',
            field=models.TextField(null=True),
        ),
    ]
